x-common-settings: &common-settings
  build:
    context: .
    dockerfile: Dockerfile
  depends_on:
    - db
  environment:
    - "USE_TAILWINDCSS_CDN=true"
  volumes:
    - .:/src:cache
    - django-media:/src/media
    - django-static:/src/static

services:

  db:
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    env_file:
      - ".env"
    image: "pgautoupgrade/pgautoupgrade:latest"
    init: true
    user: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  web:
    <<: *common-settings
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000", "--skip-checks"]
    entrypoint: /src/docker-entrypoint.sh
    env_file:
      - ".env"
    init: true
    ports:
      - "8000:8000"
    tty: true

  worker:
    <<: *common-settings
    command: ["python", "manage.py", "qcluster", "--skip-checks"]
    env_file:
      - ".env"
    init: true
    volumes:
      - .:/code
      - django-media:/code/media
      - django-static:/code/static

volumes:
  django-media:
  django-static:
  postgres-data:
