# https://github.com/charliermarsh/ruff#ruff

line-length = 120
select = [
    'B',  # flake8-bugbear
    'E',  # pycodestyle errors
    'F',  # pyflakes
    'I',  # iSort
    'W',  # pycodestyle warnings
    'B9',
]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["A", "B", "C", "D", "E", "F", "I"]
unfixable = []

exclude = [
    ".git",
    "*/static/*",
]

[isort]
known-first-party = ["automation"]
split-on-trailing-comma=true
